ahyatt/ekg

- ekg.el
First off, thanks for the package - I really like the concept!
This is an attempt to fix an issue with destructive sorting of tag lists when calling`ekg-tags-display`, which can influence operations holding a reference to the provided tag list (notably `ekg--show-notes`). A quick demonstration of the problem can be done with this code (when run without my suggested patch):
```elisp
(let ((ekg-db-file "tmp.sql")
(tags '("tags/a" "tags/b")))
(ekg--close)
(when (file-exists-p ekg-db-file)
(delete-file ekg-db-file))
(mapcar #'ekg-save-note
(list (ekg-note-create "a" ekg-capture-default-mode
'("tag/a"))
(ekg-note-create "b" ekg-capture-default-mode
'("tag/b"))))
(call-interactively #'ekg-show-notes-with-any-tags))
```
If the tags are selected in order ("tags/a" "tags/b") then the resulting …
> change tags-display to non-destructively sort tags

- ekg.el
If I call `ekg-show-notes-latest-captured' without first having called another function that connects to ekg database I get an error. This fixes that issue.
We might want to consider a `ekg-with-db` macro, similar to magit-with-editor and other macros that ensure a resource is available.
> ekg-show-notes-latest-captured: Ensure database is connected

- ekg.el
As commit message suggested, `kill-line' pollutes kill-ring, we try to avoid that.
> Replace `kill-line` with `delete-line` to avoid polluting kill-ring

- ekg.el
Quick deletion a note using the universal argument: `C-u d`.
The user can also assign a custom keybinding for quick deletion. For example, `(define-key ekg-notes-mode-map (kbd "M-d") (lambda () (interactive) (ekg-notes-delete t)))`
> Added ability to delete a note without a pompt

- ekg.el
Discussion at #55.
1. This commit would make mode change available in `ekg-edit-mode`
(previously in `ekg-capture-mode` only).
2. The function name is changed from `ekg-capture-change-mode` to
`ekg-change-mode`.
> Allow to change mode in ekg-edit-mode

- README.org
- doc/ekg.org
- doc/ekg.texi
Previously:
b45efb0: `ekg-rename-tag` renamed to `ekg-global-rename-tag`
71c0641: `ekg-capture-acceptable-mode` renamed to `ekg-acceptable-mode`
71c0641: `ekg-capture-change-mode` renamed to `ekg-change-mode`
This PR updates the related doc.
> Update doc for name changes in b45efb0 and 71c0641

- doc/ekg.org
- doc/ekg.texi
- ekg-logseq-test.el
- ekg-logseq.el
- ekg-org-roam.el
- ekg-test.el
- ekg.el
Discussion: https://github.com/ahyatt/ekg/discussions/74
1. Usage of key/val form in parameter improves readability/flexibility.
2. Any essential key that is nil, would be set to default vaule
1). text: nil --> ""
2). tags: nil --> (ekg-date-tag), even when ekg-template-tag set nil
3). mode: nil --> ekg-capture-default-mode
4). id: --> (ekg--generate-id)
> Use key/val parameter in `ekg-note-create` & `ekg-capture`

- ekg.el
Discussion: https://github.com/ahyatt/ekg/discussions/80 .
This commit sets all the capture/edit/notes mode buffers' inital `buffer-modified-p` status to nil.
> Set initial buffer-modified-p state to nil

- ekg.el
```
ekg.el:1493:17: Warning: the function ‘org-activate-links’ is not known to be defined.
ekg.el:1003:10: Warning: the function ‘org-redisplay-inline-images’ is not  known to be defined.
ekg.el:819:55: Warning: the function ‘org-open-at-point’ is not known to be defined.
```
> Suppress byte-compile warnings

- ekg-logseq-test.el
- ekg.el
This PR is to address:
1. the remaining issue of tags reversing
Before save:
```
Tags: test 1, test 2, test 3, test 4
```
After save and reopen note:
```
Tags: test 4, test 3, test 2, test 1
```
2. Ensure :titled/title value to be a list, to get `ekg-capture-url` & `ekg-capture-file` working again.
3. Display titles at multiple lines in `ekg-notes-mode`.
Related discussion: #110 .
> Fix tags reversing; ensure listp of `:titled/title` value; support multiple title lines in `ekg-notes-mode`

- ekg.el
Hello @ahyatt,
1. For `ekg-notes-select-and-browse-url`, since title in the let-binding is a list already, no need to wrap it with (list ...). Otherwise, only ONE title in notes with multi-titles will be collected.
2. Typos in `ekg--metadata-on-insert-behind`
> Remove extra `list` in `ekg-notes-select-and-browse-url` & Fix typos

- README.org
- ekg-auto-save.el
- ekg.el
Why this commit:
I personally want to have an abort function, so that I could decide where the note should go. Even the note has been auto-saved as draft by `ekg-auto-save-mode` (my personal branch), with `ekg-capture-abort`, the note still could go to trash. Or when I edit a note but later I decide not to save it at all, `ekg-edit-abort` could abort all the edits.
Changes in this commit:
1. In `ekg-edit-mode`: abort edit -> restore note to its original state. (Except for modification time: `ekg-save-note` recalculates it finally. Q: Any function to compare the new note vs the note in db: if value are the same, don't update the modification time?)
2. In `ekg-capture-mode`: abort capture -> trashing the note.
3. Clean up some whitespaces and bad indentations around the edits.
This commit …
> Add ekg-capture/edit-abort function

- ekg-auto-save.el
- ekg.el
Hello Andrew,
In this PR, several changes are made:
1. Internalize func name:
ekg-kill-buffer-query-function -> ekg--kill-buffer-query-function ;
ekg-header-line-format  -> ekg--header-line-format
2. Remove redundant code in the definition of ekg-capture-mode, which is already included in `(ekg--set-local-variables)`
3. `ekg-clean-dup-tags` should act on every tag, instead of only the incomplete `(ekg-tags)`.
4. Insert newest note on top of ekg-notes-mode by default for easy browsing. The cursor will jump to the the top of buffer on every refresh. Put the newest note on top will make it easy to find.
5. Also insert newly captured note to the ekg-show-notes-latest-{modified,captured} buffer.
6. Refresh only the edited note, instead of refreshing all the notes for better performance, and …
> Several trivial changes

- doc/ekg.org
- ekg-denote-test.el
- ekg-denote.el
Ekg denote integrate. Ability to export ekg notes to denote. I closed the order pull request and created a new one. I am new to GitHub/git, so not sure if there was a better way to handle this. I am not sure what happens to the close requests.
> Ekg denote from development branch

- doc/ekg.org
- doc/ekg.texi
- ekg-test.el
- ekg.el
This fixes behavior on markdown-mode, and makes tag behavior in the metadata work with typing as well as completion.
> Don't rely on completion exit, detect completed tags manually

- doc/ekg.org
- doc/ekg.texi
- ekg.el
On second thought, the minor UI / functionality changes in this version aren't quite enough to give it a full version number.
> Set version number to 0.6.1

- ekg-denote-test.el
- ekg-denote.el
Updated the documentation string to fix following linting errors (see during code checkin pipeline execution)
```
[00:00.082]  Linting file ‘ekg-denote.el’
[00:00.094]  ekg-denote.el:38: You should have a section marked ";;; Code:"
[00:00.094]  ekg-denote.el:26: There should be two spaces after a period
[00:00.094]  ekg-denote.el:27: There should be two spaces after a period
[00:00.095]  ekg-denote.el:21: There should be two spaces after a period
[00:00.097]  ekg-denote.el:95: First line is not a complete sentence
[00:00.098]  ekg-denote.el:141: Documentation strings should not start or end with whitespace
[00:00.099]  ekg-denote.el:162: First sentence should end with punctuation
[00:00.101]  ekg-denote.el:192: Error messages should *not* end with a period
[00:00.102]  Found 8 warnings in …
```
> denote-export: linting and test failures

- ekg.el
This is different than what is done now, which is to show it in another window (making a new window if necessary).
This will fix https://github.com/ahyatt/ekg/issues/160
> When showing ekg notes, open the notes in the current window

- doc/ekg.org
- doc/ekg.texi
- ekg-llm-test.el
- ekg-llm.el
Add ID to the JSON, if interesting.
Add any properties that have a label defined.
Remove some duplication of the properties.
Sort to get stable JSON (really just needed for tests).
Add a test for the JSONification.
> Improve the LLM json representation of past notes for LLM context

- contrib/ekg-email.el
- doc/ekg.org
- doc/ekg.texi
ekg-email is a way to store email metadata, and import it from gnus, and use it to display notes based on email addresses.
> Add a contrib directory, and add the ekg-email extension

- doc/ekg.org
- doc/ekg.texi
- ekg.el
`ekg-setup-notes-buffer` `setq-local` of `default-directory` to `ekg-db-file` parent directory.
The intention here is that the notes buffer should default to the parent directory of the user's `ekg-db-file`.  I was surprised when evaluating `ekg-show-notes-latest-captured` (and similar functions), that the `"*ekg <FOO>*"` notes buffer defaulted to whichever directory the `ekg-show-<FOO>` function was called-interactively from.  I expected these types of ekg commands would default to a consistent location. It makes more sense to me that the consistent location be the parent directory of the `ekb-db-file` rather than an arbitrary directory that potentially changes each time a notes buffer is presented. Note, the first attempt at commit …
> `ekg-setup-notes-buffer' `setq-local' `default-directory' to `ekg-db-file' parent directory.

- README.org
- doc/ekg.org
- doc/ekg.texi
- ekg-llm.el
- ekg.el
Also update the version to 0.7.0.
This implements the querying in https://github.com/ahyatt/ekg/issues/195, and also the full-text search discussed in https://github.com/ahyatt/ekg/discussions/109.
> Add text queries with ekg-show-notes-for-query via new triples-fts

- doc/ekg.org
- doc/ekg.texi
- ekg-embedding.el
- ekg-llm.el
ekg-embedding was not always being called when embedding commands were issues, so in some cases, users could get errors on saving messages.
> Support multiple providers in ekg-llm, call ekg-embedding-connect

- doc/ekg.org
- doc/ekg.texi
- ekg-embedding.el
- ekg-test.el
- ekg.el
Introduces a new customizable variable `ekg-truncation-method` that allows you to select the method for text truncation. This can be set to 'word' (default) or 'character'.
This change addresses issue #205 (from the original repository ahyatt/ekg) where word-based truncation is not suitable for Asian languages that do not use spaces for word separation.
Modifications:
- Added `defcustom ekg-truncation-method` in `ekg.el`.
- Updated `ekg-truncate-at` in `ekg.el` to respect `ekg-truncation-method`, interpreting the `num` argument as words or characters accordingly.
- Updated `ekg-embedding-text-selector-initial` in `ekg-embedding.el` to also respect `ekg-truncation-method` for selecting text for embeddings.
- Added ERT tests in `ekg-test.el` to cover both word and character-based truncation …
> Add character-based text truncation option
